package River;

enum TokenTypes {
    
    //1 CHAR TOKEN
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET, COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, COLON, AT, TILDE,

    //1 OR 2 CHAR TOKEN 
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, ARROW,

    //lITERAL TOKEN
    IDENTIFIER, STRING, NUMBER, WATERFLOW, 

    //KEYWORDS
    AND, ELSE, FALSE, FUN, IF, NIL, OR, PRINT, RETURN, TRUE, VAR, WHILE, FLOW, DAM, WHEN, DEFAULT, INFLOW, LEVEL, PLOT, EOF, FOR


}
